name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Give execute permission to gradlew
        run: |
          chmod +x ./MonApp/gradlew
          chmod +x ./MonApp/gradle/wrapper/gradle-wrapper.jar

      - name: Build APK
        run: |
          cd MonApp
          ./gradlew clean build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: MonApp/app/build/outputs/apk/debug/app-debug.apk
